export var prompt = [
    {text:"input: example : official country names of the countries ['usa','congo'] .the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['United States of America', 'Democratic Republic of the Congo']"},
    {text:"input: example : official country names of the countries ['china'] .the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['People's Republic of China']"},
    {text:"input: example : official country names of the countries ['china','taiwan','japan','singapore','Papua New Guinea'] .the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['People's Republic of China', 'Republic of China', 'Japan', 'Republic of Singapore', 'Independent State of Papua New Guinea']"},
    {text:"input: example : official country names of the countries ['romania'] .the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['Romania']"},
    {text:"input: example : official country names of the countries ['uae','singapore','russia'] .the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['United Arab Emirates', 'Republic of Singapore', 'Russian Federation']"},
    {text:"input: example : official country names of the countries ['isreal','cuba'] .the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['State of Israel', 'Republic of Cuba']"},
    {text:"input: example : official country names of the countries ['isreal','cuba'] .the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['State of Israel', 'Republic of Cuba']"},
    {text:"input: example : official country names of the countries [ 'Niger' ] .the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['Republic of Niger']"},
    {text:"input: example : official country names of the countries ['Costa Rica','Uruguay'] .the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['Republic of Costa Rica', 'Oriental Republic of Uruguay']"},
    {text:"input: example : official country names of the countries ['Yemen','Haiti','Belgium'].the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['Republic of Yemen', 'Republic of Haiti', 'Kingdom of Belgium']"},
    {text:"input: example : official country names of the countries ['North Korea','Palau','Montenegro','Nigeria'].the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['Democratic People's Republic of Korea', 'Republic of Palau', 'Montenegro', 'Federal Republic of Nigeria']"},
    {text:"input: example : official country names of the countries [ 'Slovakia', 'Georgia', 'Tokelau', 'United States Virgin Islands' ].the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['Slovak Republic', 'Georgia', 'Tokelau', 'United States Virgin Islands']"},
    {text:"input: example : official country names of the countries ['Guadeloupe','Bahrain'].the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['Guadeloupe', 'Bahrain']"},
    {text:"input: example : official country names of the countries [ 'Cape Verde', 'Faroe Islands', 'Turkey', 'Tokelau' ].the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['Republic of Cabo Verde', 'Faroe Islands', 'Republic of Turkey', 'Tokelau']"},
    {text:"input: example : official country names of the countries ['United States','Laos'].the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['United States', 'Lao People's Democratic Republic']"},
    {text:"input: example : official country names of the countries [ 'Saint Barthelemy', 'Curacao', 'Equatorial Guinea', 'Tunisia' ].the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['Saint Barthélemy', 'Curaçao', 'Equatorial Guinea', 'Tunisia']"},
    {text:"input: example : official country names of the countries [ 'Guam', 'Chile', 'Mexico', 'Gibraltar', 'Bolivia' ].the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['Guam', 'Republic of Chile', 'United Mexican States', 'Gibraltar', 'Plurinational State of Bolivia']"}, 
    {text:"input: example : official country names of the countries [ 'Suriname', 'Vatican City', 'Puerto Rico' ].the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['Republic of Suriname', 'Vatican City State', 'Puerto Rico']"}, 
    {text:"input: example : official country names of the countries ['Curacao','Mauritius','Niue','Madagascar','Armenia','Sao Tome and Principe','Kazakhstan','Palestine','France'].the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['Curaçao', 'Mauritius', 'Niue', 'Madagascar', 'Republic of Armenia', 'Democratic Republic of São Tomé and Príncipe', 'Republic of Kazakhstan', 'State of Palestine', 'French Republic']"}, 
    {text:"input: example : official country names of the countries [ 'French Polynesia' ].the output must contain only the name of the official countries in an array.the output must not be code"},
    {text:"['French Polynesia']"}, 

]